# -*- coding: utf-8 -*-
"""Exercício_Python_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15N8N3CA282PWrYjIgFGakjIgmPtrwjD9

**Exercício 1 - Aquecimento de Python para Ciência de Dados**

1. Imprima "Hello, World!" no console.
"""

print("Hello, World!")

"""2. Crie uma variável x com valor 10 e imprima seu valor."""

x = 10
print(x)

"""3. Some dois números e exiba o resultado."""

x = 10
y = 20
print(x + y)

"""4. Verifique se um número é par ou ímpar.

"""

numero = 5
if numero % 2 == 0:
  print('par')
else:
  print('impar')

"""5. Crie uma função que receba dois números e retorne a soma deles."""

def soma(n1, n2):
    return n1 + n2

n1 = 10
n2 = 20
print(soma(n1, n2))

"""6. Crie uma lista com os números de 1 a 5 e imprima-a.

"""

lista = [1,2,3,4,5]
print(lista)

"""7. Adicione o número 6 à lista criada na questão anterior.

"""

lista = [1,2,3,4,5]

lista = lista + [6]

print(lista)

"""8. Remova o número 3 da lista."""

lista = [1,2,3,4,5]

lista.remove(3)

print(lista)

"""9. Acesse o terceiro elemento da lista."""

lista = [1,2,3,4,5]

retorne = lista[3]

print(retorne)

"""10. Imprima o tamanho da lista."""

lista = [1,2,3,4,5]

retorne = len(lista)

print(retorne)

"""11. Crie um dicionário com informações de um carro (marca, modelo, ano)."""

carro = {
    "marca": "Ford",
    "modelo": "Mustang",
    "ano": 1964
}

print(carro)

"""12. Acesse o valor associado à chave "marca" no dicionário."""

carro = {
    "marca": "Ford",
    "modelo": "Mustang",
    "ano": 1964
}

retorne = carro["marca"]

print(retorne)

"""13. Adicione uma nova chave "cor" com valor "preto" ao dicionário."""

carro = {
    "marca": "Ford",
    "modelo": "Mustang",
    "ano": 1964
}

carro["cor"] = "preto"

print(carro)

"""14. Verifique se a chave "modelo" existe no dicionário.

"""

carro = {
    "marca": "Ford",
    "modelo": "Mustang",
    "ano": 1964
}

if "modelo" in carro:
  print("Existe")
else:
  print("Não existe")

"""15. Itere sobre as chaves do dicionário e imprima cada uma delas."""

carro = {
    "marca": "Ford",
    "modelo": "Mustang",
    "ano": 1964
}

for chaves in carro:
  print(chaves)

"""15. Itere sobre as chaves do dicionário e imprima cada uma delas."""

carro = {
    "marca": "Ford",
    "modelo": "Mustang",
    "ano": 1964
}

for chaves in carro:
  print(chaves)

"""17. Crie uma função que receba uma lista e retorne a soma dos elementos."""

def soma(lista):
    soma = 0
    for i in lista:
        soma += i
    return soma

lista = [1,2,3,4,5]
print(soma(lista))

"""18. Crie uma função que receba um dicionário e retorne todas as suas chaves.

"""

def chaves(dicionario):
    return dicionario.keys()


print(chaves(dicionario))

"""
19. Crie uma função que receba um dicionário e imprima chave e valor em linhas separadas."""

def chave_valor(dicionario):
    for chave, valor in dicionario.items():
        print(chave, valor)


chave_valor(dicionario)

"""20. Crie uma classe chamada Pessoa com atributos nome e idade, e um método que imprima esses dados."""

class Pessoa:
    def __init__(self, nome, idade):
        self.nome = nome
        self.idade = idade

    def imprimir(self):
        print("Nome:", self.nome)
        print("Idade:", self.idade)

pessoa1 = Pessoa("Lucas", 25)



pessoa1.imprimir()
pessoa2.imprimir()