# -*- coding: utf-8 -*-
"""Exercício_Python_1 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/174IBBXc6x51uv--8OAjXqo4lGdWqjCc-

**Exercício 1 - Aquecimento de Python para Ciência de Dados**

1. Imprima "Hello, World!" no console.
"""

print("Hello, World")

"""2. Crie uma variável x com valor 10 e imprima seu valor."""

x = 10
print(x)

"""3. Some dois números e exiba o resultado."""

print(f"A soma de {num1} e {num2} é: {resultado}")

"""4. Verifique se um número é par ou ímpar.

"""



"""5. Crie uma função que receba dois números e retorne a soma deles."""

resultado = somar_numeros(5, 7)
print(f"A soma é: {resultado}")

"""6. Crie uma lista com os números de 1 a 5 e imprima-a.

"""

numeros = [1, 2, 3, 4, 5]
print(numeros)

"""7. Adicione o número 6 à lista criada na questão anterior.

"""

numeros = [1, 2, 3, 4, 5,6]
print(numeros)

"""8. Remova o número 3 da lista."""

numeros = [1, 2, 4, 5,6]
print(numeros)

"""9. Acesse o terceiro elemento da lista."""

numeros = [1, 2, 3, 4, 5]
terceiro_elemento = numeros[3]
print(terceiro_elemento)

"""10. Imprima o tamanho da lista."""



"""11. Crie um dicionário com informações de um carro (marca, modelo, ano)."""

carro = {
    "marca": "Toyota",
    "modelo": "Corolla",
    "ano": 2020
}

"""12. Acesse o valor associado à chave "marca" no dicionário."""

print(marca_do_carro)

"""13. Adicione uma nova chave "cor" com valor "preto" ao dicionário."""

carro = {
    "marca": "Toyota",
    "modelo": "Corolla",
    "ano": 2020,
    "cor": "Preto",
}

"""14. Verifique se a chave "modelo" existe no dicionário.

"""

if "modelo" in carro:
    print("A chave 'modelo' existe no dicionário.")
else:
    print("A chave 'modelo' não existe no dicionário.")

"""15. Itere sobre as chaves do dicionário e imprima cada uma delas."""



"""15. Itere sobre as chaves do dicionário e imprima cada uma delas."""



"""17. Crie uma função que receba uma lista e retorne a soma dos elementos."""



"""18. Crie uma função que receba um dicionário e retorne todas as suas chaves.

"""



"""
19. Crie uma função que receba um dicionário e imprima chave e valor em linhas separadas."""



"""20. Crie uma classe chamada Pessoa com atributos nome e idade, e um método que imprima esses dados."""

