# -*- coding: utf-8 -*-
"""Exercício_Python_1 resolução.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XSoXtfZBEcJ5LpQvEB3eqk9ZtSZjylJh

**Exercício 1 - Aquecimento de Python para Ciência de Dados**

1. Imprima "Hello, World!" no console.
"""

print ("Hello Word")

"""2. Crie uma variável x com valor 10 e imprima seu valor."""

v = 10
print (v)

"""3. Some dois números e exiba o resultado."""

a = 5
b =2
c= a+b

print (c)

"""4. Verifique se um número é par ou ímpar.

"""

a = 6

if (a%2==0):
    print ("numero é par")
else:
    print ("numero é impar")

"""5. Crie uma função que receba dois números e retorne a soma deles."""

def somar ( a,b):
    resultado = a+b
    return resultado

resultado = somar (4,7)
print (resultado)

"""6. Crie uma lista com os números de 1 a 5 e imprima-a.

"""

lista = [1,2,3,4,5]

print (lista)

"""7. Adicione o número 6 à lista criada na questão anterior.

"""

lista.append(6)
print (lista)

"""8. Remova o número 3 da lista."""

lista.remove (3)
print (lista)

"""9. Acesse o terceiro elemento da lista."""

print (lista[2])

"""10. Imprima o tamanho da lista."""

tam = len(lista)
print (tam)

"""11. Crie um dicionário com informações de um carro (marca, modelo, ano)."""

carro = {
    "marca" : "Fiat",
    "modelo": "Argo",
    "ano": 2024
}

print (carro)

"""12. Acesse o valor associado à chave "marca" no dicionário."""

print (carro["marca"])

"""13. Adicione uma nova chave "cor" com valor "preto" ao dicionário."""

carro ["cor"] = "Preto"

"""14. Verifique se a chave "modelo" existe no dicionário.

"""

if "modelo" in carro:
  print("Existe")
else:
  print("Não Existe")

"""15. Itere sobre as chaves do dicionário e imprima cada uma delas."""

for chave in carro:
 print(chave)

"""15. Itere sobre as chaves do dicionário e imprima cada uma delas."""

for chave in carro:
 print(chave)

"""17. Crie uma função que receba uma lista e retorne a soma dos elementos."""

def somaelementos(lista):
  return sum(lista)

print(somaelementos([1,2,3,4,5]))

"""18. Crie uma função que receba um dicionário e retorne todas as suas chaves.

"""

def chaves(dicionario):
    return dicionario.keys()

    carro = {
        "marca": "Tesla",
        "modelo": "Cibertruck",
        ano: 2023
    }

print (chaves(carro))

"""
19. Crie uma função que receba um dicionário e imprima chave e valor em linhas separadas."""

def imprime_chavevalor(dicionario):
    for chave, valor in dicionario.items():
        print(f"Chave: {chave}")
        print(f"Valor: {valor}\n")

dicionario_exemplo = {
    "marca": "Honda",
    "modelo": "Civic",
    "ano": 1998,
    "cor": "branco"
}

imprime_chavevalor(dicionario_exemplo)

"""20. Crie uma classe chamada Pessoa com atributos nome e idade, e um método que imprima esses dados."""

class Pessoa:
    def __init__(self, nome, idade):
        self.nome = nome
        self.idade = idade

    def imprime_dados(self):
        print(f"Nome: {self.nome}")
        print(f"Idade: {self.idade}")


pessoa1 = Pessoa("Maria Eduarda", 22)
pessoa1.imprime_dados()