# -*- coding: utf-8 -*-
"""Exercício_Python_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T9zNBu4s72hZEwR_FXP9SlxR_NUv-GAW

**Exercício 1 - Aquecimento de Python para Ciência de Dados**

1. Imprima "Hello, World!" no console.
"""

print('Hello world!')

"""2. Crie uma variável x com valor 10 e imprima seu valor."""

x = 10
print(x)

"""3. Some dois números e exiba o resultado."""

x = 2
y = 3
print(x + y)

"""4. Verifique se um número é par ou ímpar.

"""

num = int(input('Digite um número: '))
if num % 2 == 0:
    print(f'O número {num} é par')
else:
    print(f'O número {num} é ímpar')

"""5. Crie uma função que receba dois números e retorne a soma deles."""

num = int(input('Digite um número: '))
num2 = int(input('Digite um número: '))
soma = num + num2
print('A soma dos números é: '+ str(soma))

"""6. Crie uma lista com os números de 1 a 5 e imprima-a.

"""

numeros = []
print("Lista vazia", numeros)
for i in range (0,5):
     numero = int(input("Informe um numero: "))
     numeros.append(numero)
print("Lista completa", numeros)

"""7. Adicione o número 6 à lista criada na questão anterior.

"""

numeros = []
print("Lista vazia", numeros)

for i in range(0, 5):
    numero = int(input("Informe um número: "))
    numeros.append(numero)

numeros.append(6)

print("Lista completa com o número 6:", numeros)

"""8. Remova o número 3 da lista."""

numeros = []
print("Lista vazia", numeros)

for i in range(0, 5):
    numero = int(input("Informe um número: "))
    numeros.append(numero)

numeros.append(6)

print("Lista completa com o número 6:", numeros)
if 3 in numeros:
    numeros.remove(3)
    print("Lista após remover o número 3:", numeros)

"""9. Acesse o terceiro elemento da lista."""

numeros = []
print("Lista vazia", numeros)

for i in range(0, 5):
    numero = int(input("Informe um número: "))
    numeros.append(numero)

numeros.append(6)

print("Lista completa com o número 6:", numeros)
if 3 in numeros:
    numeros.remove(3)
    print("Lista após remover o número 3:", numeros)

if len(numeros) >= 3:
    terceiro_elemento = numeros[2]
    print("O terceiro elemento da lista é:", terceiro_elemento)

"""10. Imprima o tamanho da lista."""

numeros = []
print("Lista vazia", numeros)

for i in range(0, 5):
    numero = int(input("Informe um número: "))
    numeros.append(numero)

numeros.append(6)

print("Lista completa com o número 6:", numeros)
if 3 in numeros:
    numeros.remove(3)
    print("Lista após remover o número 3:", numeros)

if len(numeros) >= 3:
    terceiro_elemento = numeros[2]
    print("O terceiro elemento da lista é:", terceiro_elemento)

numeros = []
tamanho_lista = len(numeros)
print(tamanho_lista)

"""11. Crie um dicionário com informações de um carro (marca, modelo, ano)."""

carro = {
    "marca": "Toyota",
    "modelo": "SW4",
    "ano": 2023
}

print("Informações do carro:", carro)

"""12. Acesse o valor associado à chave "marca" no dicionário."""

carro = {
    "marca": "Toyota",
    "modelo": "SW4",
    "ano": 2023
}
marca = carro["marca"]
print("Marca do carro:", marca)

"""13. Adicione uma nova chave "cor" com valor "preto" ao dicionário."""

carro["cor"] = "preto"
print("Informações atualizadas do carro:", carro)

"""14. Verifique se a chave "modelo" existe no dicionário.

"""

if "modelo" in carro:
    print("A chave 'modelo' existe no dicionário.")

"""15. Itere sobre as chaves do dicionário e imprima cada uma delas."""

carro["cor"] = "preto"
for chave in carro:
 print(chave)

"""17. Crie uma função que receba uma lista e retorne a soma dos elementos."""

def soma_lista(lista):
    return sum(lista)
minha_lista = [7,2,10,5]
resultado = soma_lista(minha_lista)
print(f"A soma dos elementos da lista é: {resultado}")

"""18. Crie uma função que receba um dicionário e retorne todas as suas chaves.

"""

def chaves(dicionario):
    return dicionario.keys()

dicionario = {
    "marca": "Toyota",
    "modelo": "SW4",
    "ano": 2023
}
print(chaves(dicionario))

"""
19. Crie uma função que receba um dicionário e imprima chave e valor em linhas separadas."""

def recebe_dados(dicionario):
  for chave, valor in dicionario.items():
        print(f"Chave: {chave}")
        print(f"Valor: {valor}\n")

recebe_dados(carro)

"""20. Crie uma classe chamada Pessoa com atributos nome e idade, e um método que imprima esses dados."""

class Pessoa:
    def __init__(self, nome, idade):
        self.nome = nome
        self.idade = idade
    def imprimir_dados(self):
        print(f"Nome: {self.nome}, Idade: {self.idade}")

pessoa1 = Pessoa("Myllena", 21)
pessoa1.imprimir_dados()